"""Initial simplified schema

Revision ID: 102cf96663ea
Revises:
Create Date: 2025-11-05 13:47:46.379948

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

import snore.database.types

# revision identifiers, used by Alembic.
revision: str = "102cf96663ea"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "algorithm_configs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("algorithm_name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column(
            "parameters_json", snore.database.types.ValidatedJSON(), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "performance_metrics_json",
            snore.database.types.ValidatedJSONWithDefault(),
            nullable=True,
        ),
        sa.Column("last_updated", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("algorithm_name"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("height_cm", sa.Integer(), nullable=True),
        sa.Column(
            "settings",
            snore.database.types.ValidatedJSONWithDefault(),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("length(username) > 0", name="chk_username"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "days",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("session_count", sa.Integer(), nullable=True),
        sa.Column("total_therapy_hours", sa.Float(), nullable=True),
        sa.Column("obstructive_apneas", sa.Integer(), nullable=True),
        sa.Column("central_apneas", sa.Integer(), nullable=True),
        sa.Column("hypopneas", sa.Integer(), nullable=True),
        sa.Column("reras", sa.Integer(), nullable=True),
        sa.Column("ahi", sa.Float(), nullable=True),
        sa.Column("oai", sa.Float(), nullable=True),
        sa.Column("cai", sa.Float(), nullable=True),
        sa.Column("hi", sa.Float(), nullable=True),
        sa.Column("pressure_min", sa.Float(), nullable=True),
        sa.Column("pressure_max", sa.Float(), nullable=True),
        sa.Column("pressure_median", sa.Float(), nullable=True),
        sa.Column("pressure_mean", sa.Float(), nullable=True),
        sa.Column("pressure_95th", sa.Float(), nullable=True),
        sa.Column("leak_min", sa.Float(), nullable=True),
        sa.Column("leak_max", sa.Float(), nullable=True),
        sa.Column("leak_median", sa.Float(), nullable=True),
        sa.Column("leak_mean", sa.Float(), nullable=True),
        sa.Column("leak_95th", sa.Float(), nullable=True),
        sa.Column("spo2_min", sa.Float(), nullable=True),
        sa.Column("spo2_max", sa.Float(), nullable=True),
        sa.Column("spo2_mean", sa.Float(), nullable=True),
        sa.Column("spo2_avg", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("profile_id", "date", name="uq_profile_date"),
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=True),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("firmware_version", sa.String(), nullable=True),
        sa.Column("hardware_version", sa.String(), nullable=True),
        sa.Column("product_code", sa.String(), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.Column("last_import", sa.DateTime(), nullable=True),
        sa.CheckConstraint("length(manufacturer) > 0", name="chk_manufacturer"),
        sa.CheckConstraint("length(serial_number) > 0", name="chk_serial"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("day_id", sa.Integer(), nullable=True),
        sa.Column("device_session_id", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("therapy_mode", sa.String(), nullable=True),
        sa.Column("import_date", sa.DateTime(), nullable=True),
        sa.Column("import_source", sa.String(), nullable=True),
        sa.Column("parser_version", sa.String(), nullable=True),
        sa.Column(
            "data_quality_notes",
            snore.database.types.ValidatedJSONWithDefault(),
            nullable=True,
        ),
        sa.Column("has_waveform_data", sa.Boolean(), nullable=True),
        sa.Column("has_event_data", sa.Boolean(), nullable=True),
        sa.Column("has_statistics", sa.Boolean(), nullable=True),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0", name="chk_duration"
        ),
        sa.CheckConstraint("end_time >= start_time", name="chk_time_range"),
        sa.ForeignKeyConstraint(["day_id"], ["days.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "device_session_id", name="uq_device_session"),
    )
    op.create_table(
        "analysis_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("timestamp_start", sa.DateTime(), nullable=False),
        sa.Column("timestamp_end", sa.DateTime(), nullable=False),
        sa.Column(
            "programmatic_result_json",
            snore.database.types.ValidatedJSONWithDefault(),
            nullable=True,
        ),
        sa.Column(
            "llm_result_json",
            snore.database.types.ValidatedJSONWithDefault(),
            nullable=True,
        ),
        sa.Column(
            "combined_result_json",
            snore.database.types.ValidatedJSONWithDefault(),
            nullable=True,
        ),
        sa.Column("agreement_score", sa.Float(), nullable=True),
        sa.Column("processing_time_ms", sa.Integer(), nullable=True),
        sa.Column(
            "engine_versions_json",
            snore.database.types.ValidatedJSONWithDefault(),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("spo2_drop", sa.Float(), nullable=True),
        sa.Column("peak_flow_limitation", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0", name="chk_duration"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "key", name="uq_session_key"),
    )
    op.create_table(
        "statistics",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("obstructive_apneas", sa.Integer(), nullable=True),
        sa.Column("central_apneas", sa.Integer(), nullable=True),
        sa.Column("mixed_apneas", sa.Integer(), nullable=True),
        sa.Column("hypopneas", sa.Integer(), nullable=True),
        sa.Column("reras", sa.Integer(), nullable=True),
        sa.Column("flow_limitations", sa.Integer(), nullable=True),
        sa.Column("ahi", sa.Float(), nullable=True),
        sa.Column("oai", sa.Float(), nullable=True),
        sa.Column("cai", sa.Float(), nullable=True),
        sa.Column("hi", sa.Float(), nullable=True),
        sa.Column("rei", sa.Float(), nullable=True),
        sa.Column("pressure_min", sa.Float(), nullable=True),
        sa.Column("pressure_max", sa.Float(), nullable=True),
        sa.Column("pressure_median", sa.Float(), nullable=True),
        sa.Column("pressure_mean", sa.Float(), nullable=True),
        sa.Column("pressure_95th", sa.Float(), nullable=True),
        sa.Column("leak_min", sa.Float(), nullable=True),
        sa.Column("leak_max", sa.Float(), nullable=True),
        sa.Column("leak_median", sa.Float(), nullable=True),
        sa.Column("leak_mean", sa.Float(), nullable=True),
        sa.Column("leak_95th", sa.Float(), nullable=True),
        sa.Column("leak_percentile_70", sa.Float(), nullable=True),
        sa.Column("respiratory_rate_min", sa.Float(), nullable=True),
        sa.Column("respiratory_rate_max", sa.Float(), nullable=True),
        sa.Column("respiratory_rate_mean", sa.Float(), nullable=True),
        sa.Column("tidal_volume_min", sa.Float(), nullable=True),
        sa.Column("tidal_volume_max", sa.Float(), nullable=True),
        sa.Column("tidal_volume_mean", sa.Float(), nullable=True),
        sa.Column("minute_ventilation_min", sa.Float(), nullable=True),
        sa.Column("minute_ventilation_max", sa.Float(), nullable=True),
        sa.Column("minute_ventilation_mean", sa.Float(), nullable=True),
        sa.Column("spo2_min", sa.Float(), nullable=True),
        sa.Column("spo2_max", sa.Float(), nullable=True),
        sa.Column("spo2_mean", sa.Float(), nullable=True),
        sa.Column("spo2_time_below_90", sa.Integer(), nullable=True),
        sa.Column("pulse_min", sa.Float(), nullable=True),
        sa.Column("pulse_max", sa.Float(), nullable=True),
        sa.Column("pulse_mean", sa.Float(), nullable=True),
        sa.Column("usage_hours", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "waveforms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("waveform_type", sa.String(), nullable=False),
        sa.Column("sample_rate", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("mean_value", sa.Float(), nullable=True),
        sa.Column("data_blob", sa.LargeBinary(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=True),
        sa.CheckConstraint("sample_rate > 0", name="chk_sample_rate"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "waveform_type", name="uq_session_waveform"),
    )
    op.create_table(
        "analysis_feedback",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_result_id", sa.Integer(), nullable=False),
        sa.Column("feedback_type", sa.String(length=50), nullable=False),
        sa.Column("discrepancy_description", sa.Text(), nullable=True),
        sa.Column("suggested_improvement", sa.Text(), nullable=True),
        sa.Column("implemented", sa.Boolean(), nullable=True),
        sa.Column("reviewed_by", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"], ["analysis_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "detected_patterns",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("analysis_result_id", sa.Integer(), nullable=False),
        sa.Column("pattern_id", sa.String(length=100), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("duration", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("detected_by", sa.String(length=20), nullable=False),
        sa.Column(
            "metrics_json",
            snore.database.types.ValidatedJSONWithDefault(),
            nullable=True,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_result_id"], ["analysis_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("detected_patterns")
    op.drop_table("analysis_feedback")
    op.drop_table("waveforms")
    op.drop_table("statistics")
    op.drop_table("settings")
    op.drop_table("events")
    op.drop_table("analysis_results")
    op.drop_table("sessions")
    op.drop_table("devices")
    op.drop_table("days")
    op.drop_table("profiles")
    op.drop_table("algorithm_configs")
    # ### end Alembic commands ###
