"""initial_database_schema

Revision ID: be586d3cb24e
Revises:
Create Date: 2025-11-04 23:16:40.531115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "be586d3cb24e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("manufacturer", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("serial_number", sa.String(), nullable=False),
        sa.Column("firmware_version", sa.String(), nullable=True),
        sa.Column("hardware_version", sa.String(), nullable=True),
        sa.Column("product_code", sa.String(), nullable=True),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.Column("last_import", sa.DateTime(), nullable=True),
        sa.CheckConstraint("length(manufacturer) > 0", name="chk_manufacturer"),
        sa.CheckConstraint("length(serial_number) > 0", name="chk_serial"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("serial_number"),
    )
    op.create_table(
        "sessions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("device_session_id", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("therapy_mode", sa.String(), nullable=True),
        sa.Column("import_date", sa.DateTime(), nullable=True),
        sa.Column("import_source", sa.String(), nullable=True),
        sa.Column("parser_version", sa.String(), nullable=True),
        sa.Column("data_quality_notes", sa.Text(), nullable=True),
        sa.Column("has_waveform_data", sa.Boolean(), nullable=True),
        sa.Column("has_event_data", sa.Boolean(), nullable=True),
        sa.Column("has_statistics", sa.Boolean(), nullable=True),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0", name="chk_duration"
        ),
        sa.CheckConstraint("end_time >= start_time", name="chk_time_range"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("device_id", "device_session_id", name="uq_device_session"),
    )
    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("duration_seconds", sa.Float(), nullable=True),
        sa.Column("spo2_drop", sa.Float(), nullable=True),
        sa.Column("peak_flow_limitation", sa.Float(), nullable=True),
        sa.CheckConstraint(
            "duration_seconds IS NULL OR duration_seconds >= 0", name="chk_duration"
        ),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "key", name="uq_session_key"),
    )
    op.create_table(
        "statistics",
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("obstructive_apneas", sa.Integer(), nullable=True),
        sa.Column("central_apneas", sa.Integer(), nullable=True),
        sa.Column("mixed_apneas", sa.Integer(), nullable=True),
        sa.Column("hypopneas", sa.Integer(), nullable=True),
        sa.Column("reras", sa.Integer(), nullable=True),
        sa.Column("flow_limitations", sa.Integer(), nullable=True),
        sa.Column("ahi", sa.Float(), nullable=True),
        sa.Column("oai", sa.Float(), nullable=True),
        sa.Column("cai", sa.Float(), nullable=True),
        sa.Column("hi", sa.Float(), nullable=True),
        sa.Column("rei", sa.Float(), nullable=True),
        sa.Column("pressure_min", sa.Float(), nullable=True),
        sa.Column("pressure_max", sa.Float(), nullable=True),
        sa.Column("pressure_median", sa.Float(), nullable=True),
        sa.Column("pressure_mean", sa.Float(), nullable=True),
        sa.Column("pressure_95th", sa.Float(), nullable=True),
        sa.Column("leak_min", sa.Float(), nullable=True),
        sa.Column("leak_max", sa.Float(), nullable=True),
        sa.Column("leak_median", sa.Float(), nullable=True),
        sa.Column("leak_mean", sa.Float(), nullable=True),
        sa.Column("leak_95th", sa.Float(), nullable=True),
        sa.Column("leak_percentile_70", sa.Float(), nullable=True),
        sa.Column("respiratory_rate_min", sa.Float(), nullable=True),
        sa.Column("respiratory_rate_max", sa.Float(), nullable=True),
        sa.Column("respiratory_rate_mean", sa.Float(), nullable=True),
        sa.Column("tidal_volume_min", sa.Float(), nullable=True),
        sa.Column("tidal_volume_max", sa.Float(), nullable=True),
        sa.Column("tidal_volume_mean", sa.Float(), nullable=True),
        sa.Column("minute_ventilation_min", sa.Float(), nullable=True),
        sa.Column("minute_ventilation_max", sa.Float(), nullable=True),
        sa.Column("minute_ventilation_mean", sa.Float(), nullable=True),
        sa.Column("spo2_min", sa.Float(), nullable=True),
        sa.Column("spo2_max", sa.Float(), nullable=True),
        sa.Column("spo2_mean", sa.Float(), nullable=True),
        sa.Column("spo2_time_below_90", sa.Integer(), nullable=True),
        sa.Column("pulse_min", sa.Float(), nullable=True),
        sa.Column("pulse_max", sa.Float(), nullable=True),
        sa.Column("pulse_mean", sa.Float(), nullable=True),
        sa.Column("usage_hours", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_table(
        "waveforms",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("waveform_type", sa.String(), nullable=False),
        sa.Column("sample_rate", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("min_value", sa.Float(), nullable=True),
        sa.Column("max_value", sa.Float(), nullable=True),
        sa.Column("mean_value", sa.Float(), nullable=True),
        sa.Column("data_blob", sa.LargeBinary(), nullable=False),
        sa.Column("sample_count", sa.Integer(), nullable=True),
        sa.CheckConstraint("sample_rate > 0", name="chk_sample_rate"),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id", "waveform_type", name="uq_session_waveform"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("waveforms")
    op.drop_table("statistics")
    op.drop_table("settings")
    op.drop_table("events")
    op.drop_table("sessions")
    op.drop_table("devices")
    # ### end Alembic commands ###
